import img01 from '../images/01.jpg'
import img02 from '../images/02.jpg'
import img03 from '../images/03.png'
import img04 from '../images/04.jpg'
import img05 from '../images/05.jpg'
import img06 from '../images/06.jpg'
import img07 from '../images/07.jpeg'
import img08 from '../images/08.jpg'
import img09 from '../images/09.jpg'
import img10 from '../images/10.jpg'
import img11 from '../images/11.jpg'
import img12 from '../images/12.jpg'
import img13 from '../images/13.jpg'
import img14 from '../images/14.jpg'

export default () => [
  {
    title: 'Vicenta',
    abstract: 'Adaptación narrativa libre del corto Vincent, de Tim Burton. Fotonovela.',
    place: '',
    graph: 'B.',
    projections: '',
    scenography: '',
    producer: '',
    cityTime: 'Montevideo, 2014.',
    cover: img09,
  },
  {
    title: 'Trío Ibarburu “Ultramarino”',
    abstract: 'Presentación del disco Ultramarino del trío Ibarburu.',
    place: 'Sala Hugo Balzo – Auditorio del Sodre.',
    graph: 'Guillermina Umpierrez',
    projections: '',
    scenography: 'Guillermina Umpierrez / B.',
    producer: 'Fluir Management & Producción',
    cityTime: 'Montevideo, 2016.',
    cover: img01,
  },
  {
    title: 'Los cuerpos “Deste lugar”',
    abstract: 'Presentación del disco Deste lugar de Los cuerpos.',
    place: 'Sala Hugo Balzo – Auditorio del Sodre.',
    graph: '',
    projections: 'Cecilia Pérez',
    scenography: 'Melina Mota / B.',
    producer: 'Fluir Management & Producción',
    cityTime: 'Montevideo, 2017.',
    cover: img02,
  },
  {
    title: 'DVD Combo Candombero',
    abstract: 'Backstage DVD de Combo Candombero.',
    place: 'Tartamudo Bar Cultural.',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'Fluir Management & Producción',
    cityTime: 'Montevideo, 2017.',
    cover: img03,
  },
  {
    title: 'Mural en tiza',
    abstract: 'Representación del proceso de la cerveza artesanal en tiza sobre pared.',
    place: 'Shelter Patio Cervecero',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'N/A',
    cityTime: 'Montevideo, 2017.',
    cover: img04,
  },
  {
    title: 'Graffiti láser',
    abstract: 'Propuesta comunicacional creativa de TFG.',
    place: '',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'N/A',
    cityTime: 'Montevideo, 2015.',
    cover: img05,
  },
  {
    title: 'Shambies “Same Old Stories”',
    abstract: 'Presentación del disco Same Old Stories de Shambies.',
    place: '',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'N/A',
    cityTime: 'Montevideo, 2016.',
    cover: img06,
  },
  {
    title: 'Corto “La Sellada”',
    abstract: 'Cortometraje “La Sellada” – Mesa Redonda Films',
    place: '',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'N/A',
    cityTime: 'Montevideo, 2017.',
    cover: img07,
  },
  {
    title: 'Hush Puppies',
    abstract: 'Publicidad Día de la Madre Hush Puppies',
    place: '',
    graph: '',
    projections: '',
    scenography: '/ B.',
    producer: 'N/A',
    cityTime: 'Montevideo, 2017.',
    cover: img08,
  },
  {
    title: 'Nicolás Ibarburu “Casa Rodante”',
    abstract: 'Presentación del disco Casa Rodante de Nicolás Ibarburu.',
    place: 'Sala Zavala Muniz – Teatro Solís.',
    graph: 'Guillermina Umpierrez / B.',
    projections: '',
    scenography: '/ B.',
    photo: 'Javier Noceti / Pablo Delgado.',
    producer: 'Fluir Management & Producción ',
    cityTime: 'Montevideo, 2016.',
    cover: img10,
  },
  {
    title: 'Radio Palermo “De Paseo”',
    abstract: 'Videoclip del single de Radio Palermo: “De Paseo”.',
    place: '',
    graph: 'Andrea Pomar / B.',
    projections: '',
    scenography: '/ B.',
    photo: '',
    producer: 'Fluir Management & Producción ',
    cityTime: 'Montevideo, 2016.',
    cover: img11,
  },
  {
    title: 'Mural infantil',
    abstract: 'Gigantografía de una ciudad cómic en pintura acrílica sobre madera.',
    place: 'ASomma Fotografía.',
    graph: '',
    projections: '',
    scenography: 'Mercedes Fernández / B.',
    photo: '',
    producer: 'Fluir Management & Producción ',
    cityTime: 'Tala, 2017.',
    cover: img12,
  },
  {
    title: 'DVD Leo Carbajal',
    abstract: 'DVD de Leo Carbajal / Trío con Gustavo Montemurro y Martín Ibarburu',
    place: 'Estudio 4Tavella',
    graph: '',
    projections: '',
    scenography: 'Andrea Pomar / B.',
    photo: '',
    producer: 'Producción: Cuatro+',
    cityTime: 'Montevideo, 2016.',
    cover: img13,
  },
  {
    title: 'Samsung',
    abstract: 'Publicidad heladeras Samsung',
    place: 'Ignacio Rodríguez',
    graph: '',
    projections: '',
    scenography: 'Andrea Pomar / B.',
    photo: '',
    producer: 'lalala',
    cityTime: 'Montevideo, 2016.',
    cover: img14,
  },
]


